apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort # Service Type
  ports:
  - port: 80
    protocol: TCP
  selector: # 아래 label을 가진 Pod를 매핑
    app: nginx
